# Generated by Django 3.1.4 on 2020-12-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('limit_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'requests_request',
            },
        ),
    ]
